ignoredBuiltDependencies:
  - '@parcel/watcher'
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
overrides:
  brace-expansion@<1.1.13: '>=1.1.13'
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  brace-expansion@>=2.0.0 <2.0.3: '>=2.0.3'
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
  esbuild@>=0.17.0 <0.28.1: '>=0.28.1'
  immutable@>=5.0.0 <5.1.5: '>=5.1.5'
  minimatch@<3.1.3: '>=3.1.3'
  minimatch@<3.1.4: '>=3.1.4'
  minimatch@>=5.0.0 <5.1.7: '>=5.1.7'
  minimatch@>=5.0.0 <5.1.8: '>=5.1.8'
  picomatch@>=4.0.0 <4.0.4: '>=4.0.4'
  postcss@<8.5.10: '>=8.5.10'
  rollup@>=4.0.0 <4.59.0: '>=4.59.0'
  tar@<7.5.7: '>=7.5.7'
  tar@<7.5.8: '>=7.5.8'
  tar@<=7.5.10: '>=7.5.11'
  tar@<=7.5.15: '>=7.5.16'
  tar@<=7.5.2: '>=7.5.3'
  tar@<=7.5.3: '>=7.5.4'
  tar@<=7.5.9: '>=7.5.10'
  tmp@<0.2.6: '>=0.2.6'
  tmp@<=0.2.3: '>=0.2.4'
  uuid@<11.1.1: '>=11.1.1'
  vite@<=6.4.1: '>=6.4.2'
  vite@<=6.4.2: '>=6.4.3'
  vite@>=6.0.0 <=6.3.5: '>=6.3.6'
  vite@>=6.0.0 <=6.4.0: '>=6.4.1'
  vite@>=6.0.0 <=6.4.1: '>=6.4.2'
